version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"
